// Generated by CoffeeScript 1.6.3
var Migrate, fibrous, fs, mongoose, slugify,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require('fs');

mongoose = require('mongoose');

fibrous = require('fibrous');

slugify = require('slugify');

Migrate = (function() {
  function Migrate(opts, model) {
    var connection, schema, uri, _base, _base1, _ref;
    this.opts = opts;
    this.model = model;
    if (this.model == null) {
      if (typeof this.opts.mongo === 'function') {
        this.opts.mongo = this.opts.mongo();
      }
      if (this.opts.mongo.hasOwnProperty('uri')) {
        _ref = this.opts.mongo, uri = _ref.uri, opts = _ref.opts;
      } else {
        uri = this.opts.mongo;
        opts = void 0;
      }
      connection = mongoose.createConnection(uri, opts);
      schema = new mongoose.Schema({
        name: {
          type: String,
          index: true,
          unique: true,
          required: true
        },
        createdAt: {
          type: Date,
          "default": Date.now
        }
      });
      this.model = connection.model('MigrationVersion', schema, 'migration_versions');
    }
    if ((_base = this.opts).ext == null) {
      _base.ext = 'coffee';
    }
    if ((_base1 = this.opts).template == null) {
      _base1.template = "module.exports =\n  requiresDowntime: FIXME # true or false\n\n  up: (done) ->\n    done()\n\n  down: (done) ->\n    throw new Error('irreversible migration')\n\n  test: (done) ->\n    console.log 'copying development to test'\n    require('child_process').exec \"mongo test --eval \"db.dropDatabase(); db.copyDatabase('development', 'test'); print('copied')\"\", ->\n      done()";
    }
  }

  Migrate.prototype.getTemplate = function(name) {
    return this.opts.template;
  };

  Migrate.prototype.log = function() {};

  Migrate.prototype.error = function(msg) {
    throw new Error(msg);
  };

  Migrate.prototype.get = function(name) {
    var migration;
    name = name.replace(new RegExp("\." + this.opts.ext + "$"), '');
    migration = require("" + this.opts.path + "/" + name);
    migration.name = name;
    return migration;
  };

  Migrate.prototype.exists = fibrous(function(name) {
    return this.model.sync.findOne({
      name: name
    }) != null;
  });

  Migrate.prototype.test = fibrous(function(name) {
    this.log("Testing migration `" + name + "`");
    return this.get(name).sync.test();
  });

  Migrate.prototype.one = fibrous(function(name) {
    return this.sync.all([name]);
  });

  Migrate.prototype.all = fibrous(function(migrations) {
    var migration, name, _i, _len;
    if (migrations == null) {
      migrations = this.sync.pending();
    }
    for (_i = 0, _len = migrations.length; _i < _len; _i++) {
      name = migrations[_i];
      if (this.sync.exists(name)) {
        this.error("`" + name + "` has already been run");
        return false;
      }
      migration = this.get(name);
      this.log("Running migration `" + migration.name + "`");
      migration.sync.up();
      this.model.sync.create({
        name: migration.name
      });
    }
    return true;
  });

  Migrate.prototype.down = fibrous(function() {
    var migration, version;
    version = this.model.sync.findOne({}, {
      name: 1
    }, {
      sort: {
        'name': -1
      }
    });
    migration = this.get(version.name);
    this.log("Reversing migration `" + migration.name + "`");
    migration.sync.down();
    return version.sync.remove();
  });

  Migrate.prototype.pending = fibrous(function() {
    var filenames, migrationsAlreadyRun, mv, names,
      _this = this;
    filenames = fs.sync.readdir(this.opts.path).sort();
    migrationsAlreadyRun = (function() {
      var _i, _len, _ref, _results;
      _ref = this.model.sync.find();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mv = _ref[_i];
        _results.push(mv.name);
      }
      return _results;
    }).call(this);
    names = filenames.map(function(filename) {
      var match;
      if (!(match = filename.match(new RegExp("^([^_].+)\." + _this.opts.ext + "$")))) {
        return;
      }
      return match[1];
    }).filter(function(name) {
      return !!name;
    }).filter(function(name) {
      return __indexOf.call(migrationsAlreadyRun, name) < 0;
    });
    return names;
  });

  Migrate.prototype.generate = fibrous(function(name) {
    var filename, timestamp;
    name = "" + (slugify(name, '_'));
    timestamp = (new Date()).toISOString().replace(/\D/g, '');
    filename = "" + this.opts.path + "/" + timestamp + "_" + name + "." + this.opts.ext;
    fs.sync.writeFile(filename, this.getTemplate(name));
    return filename;
  });

  return Migrate;

})();

module.exports = Migrate;
